<?php
defined( 'ABSPATH' ) || exit; // Exit if accessed directly

return array(
	'enabled' => array(
		'class'		=> 'pelecard-tab pelecard-tab-general',
		'title' 	=> __( 'Enable/Disable', 'woo-pelecard-gateway' ),
		'type' 		=> 'checkbox',
		'label' 	=> __( 'Enable Pelecard', 'woo-pelecard-gateway' ),
		'default' 	=> 'yes'
	),
	'language' => array(
		'title'       	=> __( 'IFrame Language', 'woo-pelecard-gateway' ),
		'type'        	=> 'select',
		'class'       	=> 'wc-enhanced-select pelecard-tab pelecard-tab-general',
		'description' 	=> '',
		'default'     	=> 'EN',
		'desc_tip'    	=> false,
		'options'     	=> array(
			'HE' => __( 'Hebrew', 'woo-pelecard-gateway' ),
			'EN' => __( 'English', 'woo-pelecard-gateway' ),
			'RU' => __( 'Russian', 'woo-pelecard-gateway' ),
		),
	),
	'title' => array(
		'class'			=> 'pelecard-tab pelecard-tab-general',
		'title' 		=> __( 'Title', 'woo-pelecard-gateway' ),
		'type' 			=> 'text',
		'description' 	=> __( 'This controls the title which the user sees during checkout.', 'woo-pelecard-gateway' ),
		'default' 		=> __( 'Pelecard Payment', 'woo-pelecard-gateway' ),
		'desc_tip'   	=> true,
	),
	'description' => array(
		'class'	  		=> 'pelecard-tab pelecard-tab-general',
		'title'       	=> __( 'Description', 'woo-pelecard-gateway' ),
		'type'       	=> 'textarea',
		'description' 	=> __( 'Payment method description that the customer will see on your checkout.', 'woo-pelecard-gateway' ),
		'default'     	=> __( 'Pay with Pelecard', 'woo-pelecard-gateway' ),
		'desc_tip'    	=> true,
	),
	'terminal' => array(
		'class'	  		=> 'pelecard-tab pelecard-tab-terminal',
		'title' 		=> __( 'Terminal', 'woo-pelecard-gateway' ),
		'type' 			=> 'text',
		'description'	=> '',
		'default' 		=> '',
		'desc_tip' 		=> false,
	),
	'username' => array(
		'class'	  		=> 'pelecard-tab pelecard-tab-terminal',
		'title' 		=> __( 'Username', 'woo-pelecard-gateway' ),
		'type' 			=> 'text',
		'description'	=> '',
		'default' 		=> '',
		'desc_tip' 		=> false,
	),
	'password' => array(
		'class'	  		=> 'pelecard-tab pelecard-tab-terminal',
		'title'			=> __( 'Password', 'woo-pelecard-gateway' ),
		'type' 			=> 'password',
		'description' 	=> '',
		'default' 		=> '',
		'desc_tip' 		=> false,
	),
	'hook' => array(
		'class'	  		=> 'pelecard-tab pelecard-tab-terminal',
		'title' 		=> __( 'Hook Terminal', 'woo-pelecard-gateway' ),
		'type' 			=> 'message',
		'description'	=> __( 'Usually A second terminal is required to perform actions such as tokenizations, refunds, etc.', 'woo-pelecard-gateway' ),
		'default' 		=> '',
		'desc_tip' 		=> false,
	),
	'hook_terminal' => array(
		'class'	  		=> 'pelecard-tab pelecard-tab-terminal',
		'title' 		=> __( 'Terminal', 'woo-pelecard-gateway' ),
		'type' 			=> 'text',
		'description'	=> '',
		'default' 		=> '',
		'desc_tip' 		=> false,
	),
	'hook_username' => array(
		'class'	  		=> 'pelecard-tab pelecard-tab-terminal',
		'title' 		=> __( 'Username', 'woo-pelecard-gateway' ),
		'type' 			=> 'text',
		'description'	=> '',
		'default' 		=> '',
		'desc_tip' 		=> false,
	),
	'hook_password' => array(
		'class'	  		=> 'pelecard-tab pelecard-tab-terminal',
		'title'			=> __( 'Password', 'woo-pelecard-gateway' ),
		'type' 			=> 'password',
		'description' 	=> '',
		'default' 		=> '',
		'desc_tip' 		=> false,
	),
	'maxpayments' => array(
		'class'	  			=> 'pelecard-tab pelecard-tab-payment',
		'title'       		=> __( 'Max Payments', 'woo-pelecard-gateway' ),
		'type'        		=> 'number',
		'description' 		=> '',
		'default'     		=> '12',
		'desc_tip'    		=> false,
		'custom_attributes' => array('min' => 1, 'required' => 'required'),
	),
	'minpayments' => array(
		'class'	  	  		=> 'pelecard-tab pelecard-tab-payment',
		'title'       		=> __( 'Min Payments', 'woo-pelecard-gateway' ),
		'type'        		=> 'number',
		'description' 		=> __( 'If the number of minimum and maximum payments are 1 - field will not be displayed.', 'woo-pelecard-gateway' ) . '<br>' .
							   __( 'If the number of minimum and maximum payments are the same and are greater than 1, you must also enter minimum payments for credit.', 'woo-pelecard-gateway' ),
		'default'     		=> '1',
		'desc_tip'    		=> false,
		'custom_attributes' => array('min' => 1, 'required' => 'required'),
	),
	'mincredit' => array(
		'class'	  	  		=> 'pelecard-tab pelecard-tab-payment',
		'title'       		=> __( 'Min Payments For Credit', 'woo-pelecard-gateway' ),
		'type'        		=> 'number',
		'description'		=> __( 'The number represents the amount of the minimum payment required to define a credit transaction.', 'woo-pelecard-gateway' ) . '<br>' .
							   __( 'Determined in accordance to the agreement with the credit card company.', 'woo-pelecard-gateway' ) . '<br>' .
							   __( 'If you want to avoid credit transactions, you must enter a value larger than the maximum number of payments.', 'woo-pelecard-gateway' ),
		'default'     		=> '1',
		'desc_tip'    		=> false,
		'custom_attributes' => array('min' => 1, 'required' => 'required'),
	),
	'firstpayment' => array(
		'title'       => __( 'First Payment', 'woo-pelecard-gateway' ),
		'type'        => 'select',
		'class'       => 'wc-enhanced-select pelecard-tab pelecard-tab-payment',
		'description' => __( 'The initial amount should be less than the amount of the transaction.', 'woo-pelecard-gateway' ),
		'default'     => 'auto',
		'desc_tip'    => false,
		'options'     => array(
			'auto'	  => __( 'Auto', 'woo-pelecard-gateway' ),
			'manual'  => __( 'Manual', 'woo-pelecard-gateway' ),
		)
	),
	'paymentrange' => array(
		'type'        => 'payment_range'
	),
	'cardholdername' => array(
		'title'       => __( 'Card Holder Name', 'woo-pelecard-gateway' ),
		'type'        => 'select',
		'class'       => 'wc-enhanced-select pelecard-tab pelecard-tab-fields',
		'description' => '',
		'default'     => 'hide',
		'desc_tip'    => false,
		'options'     => array(
			'hide'		=> __( 'Disabled', 'woo-pelecard-gateway' ),
			'must' 		=> __( 'Required', 'woo-pelecard-gateway' ),
			'optional' 	=> __( 'Optional', 'woo-pelecard-gateway' ),
		)
	),
	'customeridfield' => array(
		'title'       => __( 'Customer Id Field', 'woo-pelecard-gateway' ),
		'type'        => 'select',
		'class'       => 'wc-enhanced-select pelecard-tab pelecard-tab-fields',
		'description' => '',
		'default'     => 'hide',
		'desc_tip'    => false,
		'options'     => array(
			'hide'		=> __( 'Disabled', 'woo-pelecard-gateway' ),
			'must' 		=> __( 'Required', 'woo-pelecard-gateway' ),
			'optional' 	=> __( 'Optional', 'woo-pelecard-gateway' ),
		)
	),
	'cvv2field' => array(
		'title'       => __( 'Cvv2 Field', 'woo-pelecard-gateway' ),
		'type'        => 'select',
		'class'       => 'wc-enhanced-select pelecard-tab pelecard-tab-fields',
		'description' => '',
		'default'     => 'hide',
		'desc_tip'    => false,
		'options'     => array(
			'hide'		=> __( 'Disabled', 'woo-pelecard-gateway' ),
			'must' 		=> __( 'Required', 'woo-pelecard-gateway' ),
			'optional' 	=> __( 'Optional', 'woo-pelecard-gateway' ),
		)
	),
	'emailfield' => array(
		'title'       => __( 'Email Field', 'woo-pelecard-gateway' ),
		'type'        => 'select',
		'class'       => 'wc-enhanced-select pelecard-tab pelecard-tab-fields',
		'description' => '',
		'default'     => 'hide',
		'desc_tip'    => false,
		'options'     => array(
			'hide'		=> __( 'Disabled', 'woo-pelecard-gateway' ),
			'must' 		=> __( 'Required', 'woo-pelecard-gateway' ),
			'optional' 	=> __( 'Optional', 'woo-pelecard-gateway' ),
			'value'		=> __( 'Required with value', 'woo-pelecard-gateway' ),
		)
	),
	'telfield' => array(
		'title'       => __( 'Tel Field', 'woo-pelecard-gateway' ),
		'type'        => 'select',
		'class'       => 'wc-enhanced-select pelecard-tab pelecard-tab-fields',
		'description' => '',
		'default'     => 'hide',
		'desc_tip'    => false,
		'options'     => array(
			'hide'		=> __( 'Disabled', 'woo-pelecard-gateway' ),
			'must' 		=> __( 'Required', 'woo-pelecard-gateway' ),
			'optional' 	=> __( 'Optional', 'woo-pelecard-gateway' ),
			'value'		=> __( 'Required with value', 'woo-pelecard-gateway' ),
		)
	),
	'splitccnumber' => array(
		'class'	  	  => 'pelecard-tab pelecard-tab-fields',
		'title' 	  => __( 'Split CC Number', 'woo-pelecard-gateway' ),
		'type' 		  => 'checkbox',
		'description' => __( 'Card field is divided into 4 groups of 4 numbers.', 'woo-pelecard-gateway' ),
		'label' 	  => __( 'Enabled', 'woo-pelecard-gateway' ),
		'default' 	  => 'no',
		'desc_tip'    => true,
	),
	'cancelbutton' => array(
		'class'	  	  => 'pelecard-tab pelecard-tab-fields',
		'title' 	  => __( 'Cancel Button', 'woo-pelecard-gateway' ),
		'type' 		  => 'checkbox',
		'description' => __( 'Cancel the order and redirect the buyer back to basket', 'woo-pelecard-gateway' ),
		'label' 	  => __( 'Enabled', 'woo-pelecard-gateway' ),
		'default' 	  => 'no',
		'desc_tip'    => true,
	),
	'freetotal' => array(
		'class'	  	  => 'pelecard-tab pelecard-tab-fields',
		'title' 	  => __( 'Free Total', 'woo-pelecard-gateway' ),
		'type' 		  => 'checkbox',
		'description' => __( 'Editable field will be displayed next to the original amount field, and the customer can add the desired amount.', 'woo-pelecard-gateway' ),
		'label' 	  => __( 'Enabled', 'woo-pelecard-gateway' ),
		'default' 	  => 'no',
		'desc_tip'    => true,
	),
	'confirmationcb' => array(
		'title'       => __( 'Confirmation CheckBox', 'woo-pelecard-gateway' ),
		'type'        => 'select',
		'class'       => 'wc-enhanced-select pelecard-tab pelecard-tab-confirmation',
		'description' => '',
		'default'     => 'hide',
		'desc_tip'    => false,
		'options'     => array(
			'false'		=> __( 'Disabled', 'woo-pelecard-gateway' ),
			'true' 		=> __( 'Enabled', 'woo-pelecard-gateway' ),
			'checked' 	=> __( 'Checked', 'woo-pelecard-gateway' ),
		)
	),
	'confirmationtext' => array(
		'class'	  		=> 'pelecard-tab pelecard-tab-confirmation',
		'title' 		=> __( 'Confirmation Text', 'woo-pelecard-gateway' ),
		'type' 			=> 'text',
		'description'	=> __( 'Free text presented to the customer when set to confirm the payment.', 'woo-pelecard-gateway' ) . '<br>' .
						   __( 'If Confirmation Link value is entered, this field will turn into a HyperLink to the same address.', 'woo-pelecard-gateway' ),
		'default' 		=> '',
		'desc_tip' 		=> false,
	),
	'confirmationurl' => array(
		'class'	  	  => 'pelecard-tab pelecard-tab-confirmation',
		'title' 	  => __( 'Confirmation Link', 'woo-pelecard-gateway' ),
		'type' 		  => 'url',
		'placeholder' => 'http://',
		'description' => __( 'HyperLink address of Confirmation Text.', 'woo-pelecard-gateway' ) . '<br>' .
						 __( 'If the field is empty Confirmation link will not be displayed.', 'woo-pelecard-gateway' ),
		'label' 	  => __( 'Enabled', 'woo-pelecard-gateway' ),
		'default' 	  => '',
		'desc_tip'    => false,
	),
	'toptext' => array(
		'class'	 		=> 'pelecard-tab pelecard-tab-appearance',
		'title' 		=> __( 'Top Text', 'woo-pelecard-gateway' ),
		'type' 			=> 'text',
		'description'	=> '',
		'default' 		=> '',
		'desc_tip' 		=> true,
	),
	'bottomtext' => array(
		'class'	 		=> 'pelecard-tab pelecard-tab-appearance',
		'title' 		=> __( 'Bottom Text', 'woo-pelecard-gateway' ),
		'type' 			=> 'text',
		'description'	=> '',
		'default' 		=> '',
		'desc_tip' 		=> true,
	),
	'supportedcards' => array(
		'title'       => __( 'Supported Cards', 'woo-pelecard-gateway' ),
		'type'        => 'multiselect',
		'class'       => 'wc-enhanced-select pelecard-tab pelecard-tab-appearance',
		'description' => __( 'Display logos of the cards supported by the system.', 'woo-pelecard-gateway' ),
		'desc_tip'    => false,
		'options'     => array(
			'Amex'		=> __( 'Amex', 'woo-pelecard-gateway' ),
			'Diners' 	=> __( 'Diners', 'woo-pelecard-gateway' ),
			'Isra' 		=> __( 'Isra', 'woo-pelecard-gateway' ),
			'Master' 	=> __( 'Master', 'woo-pelecard-gateway' ),
			'Visa'		=> __( 'Visa', 'woo-pelecard-gateway' ),
		)
	),
	'setfocus' => array(
		'title'       => __( 'Focus on field', 'woo-pelecard-gateway' ),
		'type'        => 'select',
		'class'       => 'wc-enhanced-select pelecard-tab pelecard-tab-appearance',
		'description' => '',
		'desc_tip'    => false,
		'options'     => array(
			''			=> __( 'Default (none)', 'woo-pelecard-gateway' ),
			'CC' 		=> __( 'Card Number', 'woo-pelecard-gateway' ),
			'CCH' 		=> __( 'Card Holder Name', 'woo-pelecard-gateway' ),
		)
	),
	'logourl' => array(
		'class'	  	  => 'pelecard-tab pelecard-tab-appearance',
		'title' 	  => __( 'Logo URL', 'woo-pelecard-gateway' ),
		'type' 		  => 'url',
		'placeholder' => 'https://',
		'description' => __( 'Link to customers logo file.', 'woo-pelecard-gateway' ),
		'label' 	  => __( 'Enabled', 'woo-pelecard-gateway' ),
		'default' 	  => '',
		'desc_tip'    => true,
	),
	'cssurl' => array(
		'class'	  	  => 'pelecard-tab pelecard-tab-appearance',
		'title' 	  => __( 'Css URL', 'woo-pelecard-gateway' ),
		'type' 		  => 'url',
		'placeholder' => 'https://',
		'description' => __( 'CSS file link for custom design implementation.', 'woo-pelecard-gateway' ) . '<br>' .
						 __( 'If not specified default pelecard CSS will be used.', 'woo-pelecard-gateway' ),
		'label' 	  => __( 'Enabled', 'woo-pelecard-gateway' ),
		'default' 	  => '',
		'desc_tip'    => false,
	),
	'hiddenpelecard' => array(
		'class'	  	  => 'pelecard-tab pelecard-tab-appearance',
		'title' 	  => __( 'Pelecard Logo', 'woo-pelecard-gateway' ),
		'type' 		  => 'checkbox',
		'description' => __( 'Display / hide pelecard logo.', 'woo-pelecard-gateway' ),
		'label' 	  => __( 'Enabled', 'woo-pelecard-gateway' ),
		'default' 	  => 'no',
		'desc_tip'    => true,
	),
	'tamal' => array(
		'class'			=> 'pelecard-tab pelecard-tab-tamal',
		'title' 		=> __( 'Enable/Disable', 'woo-pelecard-gateway' ),
		'type' 			=> 'checkbox',
		'description'	=> __( 'Create Invoice \ Receipt', 'woo-pelecard-gateway' ),
		'label' 		=> __( 'Enable Tamal', 'woo-pelecard-gateway' ),
		'default' 		=> 'no',
		'desc_tip' 		=> true,
	),
	'tamaluser' => array(
		'class'	  		=> 'pelecard-tab pelecard-tab-tamal',
		'title' 		=> __( 'Username', 'woo-pelecard-gateway' ),
		'type' 			=> 'text',
		'description'	=> '',
		'default' 		=> '',
		'desc_tip' 		=> false,
	),
	'tamalpassword' => array(
		'class'	  		=> 'pelecard-tab pelecard-tab-tamal',
		'title'			=> __( 'Password', 'woo-pelecard-gateway' ),
		'type' 			=> 'password',
		'description' 	=> '',
		'default' 		=> '',
		'desc_tip' 		=> false,
	),
	'tamaleseknum' => array(
		'class'	  		=> 'pelecard-tab pelecard-tab-tamal',
		'title' 		=> __( 'Esek number', 'woo-pelecard-gateway' ),
		'type' 			=> 'text',
		'description'	=> '',
		'default' 		=> '',
		'desc_tip' 		=> false,
	),
	'tamalosek' => array(
		'title'       	=> __( 'Osek Type', 'woo-pelecard-gateway' ),
		'type'        	=> 'select',
		'class'       	=> 'wc-enhanced-select pelecard-tab pelecard-tab-tamal',
		'description' 	=> '',
		'default'     	=> 0,
		'desc_tip'    	=> false,
		'options'     	=> array(
			'mursh' => __( 'Osek Mursh', 'woo-pelecard-gateway' ),
			'patur' => __( 'Osek Patur', 'woo-pelecard-gateway' ),
			'amuta' => __( 'Amuta', 'woo-pelecard-gateway' ),
		),
	),
	'tamaldoctype' => array(
		'title'       	=> __( 'Document Type', 'woo-pelecard-gateway' ),
		'type'        	=> 'select',
		'class'       	=> 'wc-enhanced-select pelecard-tab pelecard-tab-tamal',
		'description' 	=> '',
		'default'     	=> 100,
		'desc_tip'    	=> false,
		'options'     	=> array(
			'100' 	=> __( 'Hazmana', 'woo-pelecard-gateway' ),
			'300' 	=> __( 'Heshbonit Iska', 'woo-pelecard-gateway' ),
			'305' 	=> __( 'Heshbonit Mas', 'woo-pelecard-gateway' ),
			'320' 	=> __( 'Heshbonit Mas Kabala', 'woo-pelecard-gateway' ),
			'330' 	=> __( 'Heshbonit Mas Zikui', 'woo-pelecard-gateway' ),
			'400' 	=> __( 'Kabala', 'woo-pelecard-gateway' ),
			'405' 	=> __( 'Kabala Al Trumot', 'woo-pelecard-gateway' ),
			'10100' => __( 'Hazaat Mehir', 'woo-pelecard-gateway' ),
			'10301' => __( 'Heshbon Iska', 'woo-pelecard-gateway' ),
		),
	),
	'tamallanguage' => array(
		'title'       	=> __( 'Document Language', 'woo-pelecard-gateway' ),
		'type'        	=> 'select',
		'class'       	=> 'wc-enhanced-select pelecard-tab pelecard-tab-tamal',
		'description' 	=> '',
		'default'     	=> 0,
		'desc_tip'    	=> false,
		'options'     	=> array(
			'0' => __( 'Hebrew', 'woo-pelecard-gateway' ),
			'1' => __( 'English', 'woo-pelecard-gateway' ),
		),
	),
	'tamaldocremark' => array(
		'class'	  		=> 'pelecard-tab pelecard-tab-tamal',
		'title' 		=> __( 'Document Remark', 'woo-pelecard-gateway' ),
		'type' 			=> 'text',
		'description'	=> '',
		'default' 		=> '',
		'desc_tip' 		=> false,
	),
);
